# Generated by Django 4.2.9 on 2024-01-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gene', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
            ],
        ),
    ]
