# Generated by Django 4.2.9 on 2024-01-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalstapp', '0002_remove_animals_id_alter_animals_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
